module.exports = {
  BS_Chrome_Current: {
    base: 'BrowserStack',
    browser: 'chrome',
    browser_version: 'latest',
    os: 'Windows',
    os_version: '10',
  },
  BS_Firefox_Current: {
    base: 'BrowserStack',
    browser: 'firefox',
    browser_version: 'latest',
    os: 'Windows',
    os_version: '10',
  },
  BS_Safari_Current: {
    base: 'BrowserStack',
    browser: 'safari',
    browser_version: 'latest',
    os: 'OS X',
    os_version: 'High Sierra',
  },
  BS_Chrome_49: {
    base: 'BrowserStack',
    browser: 'chrome',
    browser_version: '49',
    os: 'Windows',
    os_version: '10',
  },
  BS_iphone_10: {
    base: 'BrowserStack',
    browser: 'Mobile Safari',
    browser_version: null,
    device: 'iPhone 7',
    os: 'ios',
    os_version: '10.3',
  },
  BS_iphone_7: {
    base: 'BrowserStack',
    browser: 'Mobile Safari',
    browser_version: null,
    device: 'iPhone 5S',
    os: 'ios',
    os_version: '7.0',
    real_mobile: false,
  },
  BS_MS_Edge: {
    base: 'BrowserStack',
    browser: 'edge',
    browser_version: 'latest',
    os: 'Windows',
    os_version: '10',
  },
  BS_IE_11: {
    base: 'BrowserStack',
    browser: 'ie',
    browser_version: '11.0',
    os: 'Windows',
    os_version: '7',
  },
  BS_IE_10: {
    base: 'BrowserStack',
    browser: 'ie',
    browser_version: '10.0',
    os: 'Windows',
    os_version: '7',
  },
};
